# Generated by Django 4.1.3 on 2023-03-29 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=uuid.UUID('55bf708c-5364-48ef-a29b-b2d34ce16c54'), max_length=200),
        ),
    ]
