# Generated by Django 4.1.3 on 2023-04-23 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=uuid.UUID('dc9bd17b-5518-4eb8-877b-8d9560538dd5'), max_length=200),
        ),
    ]
