# Generated by Django 4.1.3 on 2023-04-24 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=uuid.UUID('3163944d-8c43-4220-996c-63938325ec4f'), max_length=200),
        ),
    ]
