# Generated by Django 4.1.3 on 2023-05-19 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=uuid.UUID('93eac63e-e9ab-4779-9e59-c2bade443b55'), max_length=200),
        ),
    ]
