# Generated by Django 4.1.3 on 2023-05-19 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=uuid.UUID('b2f84158-eaaa-4b10-83aa-b7bc56e12a9a'), max_length=200),
        ),
    ]
