# Generated by Django 4.1.3 on 2023-05-25 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=uuid.UUID('b98df049-0165-4e1c-becb-504321793744'), max_length=200),
        ),
    ]
