# Generated by Django 4.1.7 on 2023-11-26 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(default=uuid.UUID('f5a33af1-c759-4bd0-b6b9-3780ea486961'), max_length=200),
        ),
    ]
