# Generated by Django 4.1.3 on 2023-03-11 21:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_info', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
