# Generated by Django 4.1.3 on 2023-03-11 21:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bankinfo_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankinfo',
            options={'verbose_name': 'Bank Information', 'verbose_name_plural': 'Bank Information'},
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='account_info_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='account_info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='instructions_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='instructions_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
