# Generated by Django 4.1.3 on 2023-03-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bankinfo_options_bankinfo_account_info_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='paid_status',
        ),
        migrations.RemoveField(
            model_name='cartorderproducts',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='invoice_no',
        ),
    ]
