# Generated by Django 4.1.3 on 2023-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cartorder_cod_remove_cartorder_paid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default=100, max_length=100, null=True),
        ),
    ]
