# Generated by Django 4.1.3 on 2023-05-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_prescribtion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('speciality', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Doctors')),
                ('timing', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=70)),
                ('number', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='prescription/insuarance')),
                ('prescribtion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='core.prescribtion')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
            },
        ),
    ]
