# Generated by Django 4.1.3 on 2023-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_doctor_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='details_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='details_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_ar',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
