# Generated by Django 4.1.3 on 2023-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_doctor_details_doctor_details_ar_doctor_details_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
