# Generated by Django 4.1.3 on 2023-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='image',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='number',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='prescribtion',
        ),
        migrations.RemoveField(
            model_name='prescribtion',
            name='details',
        ),
        migrations.RemoveField(
            model_name='prescribtion',
            name='details_ar',
        ),
        migrations.RemoveField(
            model_name='prescribtion',
            name='details_en',
        ),
        migrations.RemoveField(
            model_name='prescribtion',
            name='prescribtion',
        ),
        migrations.RemoveField(
            model_name='prescribtion',
            name='prescribtion_ar',
        ),
        migrations.RemoveField(
            model_name='prescribtion',
            name='prescribtion_en',
        ),
        migrations.AddField(
            model_name='prescribtion',
            name='insurance',
            field=models.ImageField(blank=True, null=True, upload_to='prescription/insurance'),
        ),
    ]
