# Generated by Django 4.1.3 on 2023-05-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_insurance_image_remove_insurance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribtion',
            name='insurance_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescription/insurance'),
        ),
        migrations.AlterField(
            model_name='prescribtion',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescrbtions', to='core.insurance'),
        ),
    ]
